# Site Info
title: ğŸ‘ˆê¹€ì´ ê¸°ìˆ  ë¸”ë¡œê·¸
tagline: "ğŸ‘ˆê¹€ì´ ê¸°ìˆ  ë¸”ë¡œê·¸"
description: "codingfox í…Œë§ˆë¥¼ ê¸°ë°˜ìœ¼ë¡œ ë§Œë“  ê¹ƒí—ˆë¸Œ ê³µë¶€ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤."
baseurl: ""
url: https://gunlog.dev
logo: "/public/logo.png"

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: "/blog/page:num"
permalink: pretty

base_date_format:
  - '%y/%m/%d'

author:
  name: GUN KIM
  description: "<b>STATE:</b> ğŸ˜í•˜ê³ ì‹¶ì€ ê²Œ ì—„ì²­ ë§ìŒ."
  contact:
    github: https://github.com/gunkim0318
    # facebook:  <hide>
    email: mailto:gunkim0318@gmail.com
# Navigation (2nd level links supported)
nav:
  Home:
    - "/"
  'All Posts':
    - "/blog/"
  Dev:
    Spring:
    Java:
    JavaScript:
    Jpa:
    Kotlin:
    React:
    Git:
  ì†ë‹¥ì†ë‹¥:
    - "/blog/categories#ì†ë‹¥ì†ë‹¥"
  About:
    - "/about/"

category_page: "/blog/categories"

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: "UA-00000000-1" # leave blank if you don't want google analytics
disqus_short_name: "gunkim" # leave blank if you don't want disqus

